config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'confirmation', to: 'pages#confirmation'
  resources :gears do
    resources :rents, only: [:destroy, :create, :update]
    resources :reviews, only: [:index, :create, :new]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  has_many :rents
  has_many :reviews
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode

  # validates :name , presence: true
  # validates :category , presence: true
  # validates :user_id , presence: true
  # validates :price , presence: true

  def self.categories
    ['cameras', 'tripods', 'lenses', 'drones']
  end
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :gear

  validates :check_in, presence: true
  validates :check_out, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :gear

  validates :description, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gears
  # has_many :rents
  has_many :reviews
  has_many :rents
  # has_many :rents, through: :gears
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :store_action

  def store_action
    return unless request.get?
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, request.fullpath)
    end
  end


  protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
          end

end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_gear, only: [:show, :edit]

  # def index
  #   if params[:search] && params[:search][:query] != ""
  #     @gears = Gear.all.select { |gear| gear.name.downcase == params[:search][:query].downcase }
  #   else
  #     @gears = Gear.all
  #   end
  # end

  def index
    if params[:button] && params[:query] != "" && Gear.all.categories.include?(params[:query])
      @gears = Gear.all.select { |gear| gear.category.downcase.include?(params[:query].downcase) }
    elsif params[:button] && params[:query] != ""
      @gears = Gear.all.select { |gear| gear.name.downcase.include?(params[:query].downcase) }
    else
      @gears = Gear.all
    end
  end

  def show
    gears = Gear.geocoded
    set_gear
    geocoded_gear = gears.where(id: params[:id])
    @markers = geocoded_gear.map do |gear|
      {
        lat: gear.latitude,
        lng: gear.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { gear: gear })
      }
    end
    @rent = Rent.new
  end

  def new
    @gear = Gear.new
  end

  def create
    @gear = Gear.new(gear_params)
    @gear.user = current_user
    if @gear.save
      redirect_to gear_path(@gear)
    else
      render :new
    end
  end

  def edit
  end


  def destroy
    set_gear
    @gear.destroy
    redirect_to gears_path
  end


  private

  def gear_params
    params.require(:gear).permit(:name, :price, :description, :category, :photo)
  end

  def set_gear
    @gear = Gear.find(params[:id])
  end

  # def after_sign_in_path_for(resource_or_scope)
  #   stored_location_for(resource_or_scope) || super
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard
    @user = current_user
    @gears = @user.gears.select { |gear| gear.rents.count >= 1 }
    @rents = @user.rents
    #@requests = @user.rents.select{ |rent| rent.request == true }
  end

  def confirmation
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @gear = Gear.find(params[:gear_id])
    @rent = Rent.new(params.require(:rent).permit(:check_in, :check_out))
    @rent.user = current_user
    @rent.gear = @gear
    @rent.total_price = maths(params[:rent][:check_in], @gear)
    @gear.update(available: false)
    if @rent.save
      redirect_to confirmation_path
    else
      render "gears/show"
    end
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy
    @gear = Gear.find(params[:gear_id])
    @gear.available = true
    @gear.save
    redirect_to dashboard_path
  end

  def update
    @rent = Rent.find(params[:id])
    @rent.request = true
    @rent.save
    redirect_to dashboard_path
  end

  private

  def maths(date, gear)
    if date != ""
      checks = date.split(" to ")
      check_in = Date.parse(checks[0])
      check_out = Date.parse(checks[1])
      days = check_out - check_in
      return days * gear.price
    else
      return 0
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @gear = Gear.find(params[:gear_id])
    @reviews = Review.select { |review| review.gear_id == @gear.id}
  end

  def new
    @gear = Gear.find(params[:gear_id])
    @review = Review.new
  end

  def create
    @gear = Gear.find(params[:gear_id])
    @review = Review.new(params.require(:review).permit(:description, :rating))
    @review.gear = @gear
    @review.user = current_user
    if @review.save
      redirect_to gear_path(@gear)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @gear = Gear.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gears/_form.html.erb
<div class="container">
  <div class="row d-flex justify-content-center my-5 py-5 login-box">
    <div class="col-md-8 border rounded py-4 px-5 shadow">
      <h5 class="text-center mb-4">List Gear</h2>
      <%= simple_form_for (gear) do |f| %>
      <%= f.input :name, class: "d-flex justify-content-center" %>
      <%= f.input :price %>
      <%= f.input :description %>
      <%= f.input :category, :collection => Gear.categories%>
      <%= f.input :address %>
      <%= f.input :photo, input_html: { class: 'hidden'} %>
      <%= image_tag "", width: 300, class: "show", id: "photo-preview" %>
      <%= f.submit "Add Equipment", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/gears/_info_window.html.erb
<p><%= @gear.name %></h2>
<p><%= @gear.price %></p>

app/views/gears/destroy.html.erb
destroy.html.erb

app/views/gears/edit.html.erb
edit.html.erb

app/views/gears/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <%= render 'shared/search-bar' %>
  </div>
<% if @gears != []  %>



    <h5 class="text-center mt-5 pb-2 border-bottom text-center"><strong>See our list of <%= params[:query] %></strong></h4>

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 justify-content-center mt-3" >
    <% @gears.each do |gear| %>
      <%= link_to gear_path(gear) do %>
        <div class="card-trip my-3 mx-2 card-height">
          <% if gear.photo.attached? %>
            <%= cl_image_tag gear.photo.key, style:"object-fit: cover; height: 217.8px;" %>
          <% else %>
            <img class="card-img-top" src="https://images.unsplash.com/photo-1518353053542-7ea33d942319?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80" alt="Card image cap">
          <% end %>
          <div class="card-trip-infos d-flex justify-content-between p-3">
            <p class="card-title"><strong><%= gear.name %></strong></p>
            <p class="card-trip-pricing">€<%= gear.price %> </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="error">
  <p class="error-message">I'm Sorry! but <%= params[:query] %> is not one of our categories!</p>
  <img src="https://res.cloudinary.com/dvdrzlpz/image/upload/v1582725914/1529054660_Ricki-Barlow-2015-WDW-Mike-Zahara_huqnck.jpg" alt="">
  </div>
  <% end %>
  <div class="d-flex justify-content-center mb-5">
    <%= link_to "Go back", root_path, class: "btn"%>
  </div>
</div>

app/views/gears/new.html.erb
<%= render 'form', gear: @gear %>

app/views/gears/show.html.erb
<!-- CAROUSEL -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @gear.photo.attached? %>
        <%= cl_image_tag @gear.photo.key, class:"d-block w-100" %>
      <% else %>
        <img class="d-block w-100" src="https://images.unsplash.com/photo-1488684430052-f2d92fb178c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1052&q=80" alt="First slide">
        <% end %>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1542908945-2d06f969cc61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1086&q=80" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1500634245200-e5245c7574ef?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- END OF CAROUSEL -->

<div class="container">
  <!-- DETAILS -->
  <div class="row py-4">
    <!-- LEFT SIDE DETAILS -->
    <div class="col-lg-8 col-sm-12">
      <div class="d-flex justify-content-between border-bottom align-items-center">
        <h4><%= @gear.name %></h4> <br><br>
        <span class="text-muted font-weight-light"><%= @gear.user.username %></span>
      </div>

      <p class="border-bottom py-3"><%= @gear.description %> <br><br>

      <div class='d-flex justify-content-between border-bottom'>
      <h4>Reviews</h4>
      <p class='numbr-revs' style="color: #FFDB58;"><%= @gear.reviews.count %></p>
      </div>

      <div>
        <% @gear.reviews.each do |review| %>
        <div class="d-flex">
          <p class='ratings'><%= review.rating %><i class='fas fa-star'></i></p>
          <p><strong style="margin-left: 10px;">  <%= review.user.username  %></strong></p>
          </div>
          <p class='border-bottom'><%= review.description %></p>
        <% end %>
          <%= link_to "new review", new_gear_review_path(@gear) %>
      </div>


      <div class="location">
        <h4 class="mb-3 border-bottom">Location</h4>
        <div id="map" style="width: 100%; height: 600px;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
    <!-- END OFLEFT SIDE DETAILS -->

    <!-- RIGHT SIDE PAYMENT DETAILS -->
    <div class="col-lg-4 col-sm-12">
      <div class="sticky-details border rounded p-4">
        <p class="border-bottom"><strong><span id="price"><%= @gear.price %></span> EUR</strong> / day</p>
        <p><strong>Dates</strong></p>
        <%= simple_form_for [@gear, @rent], method: :post do |t| %>
        <%= t.input :check_in  , as: :string, input_html: { id: "start_date" } %>
        <%= t.input :check_out, as: :string, input_html: { id: "end_date"} %>

        <p class="border-bottom"><strong>Payment details</strong></p>
        <p><%= @gear.price %> EUR x <span id="days">0</span> day(s)</p>
        <div class="d-flex justify-content-between">
          <p>Total:</p>
          <p><strong><span id="total-price">0</span> EUR</strong></p>
        </div>
        <%= t.submit "Request to rent", class: "btn btn-block" %>

        <% end %>
        <br>
        <p class="text-center">You won’t be charged yet</p>
      </div>
    </div>
    <!-- END OF RIGHT SIDE PAYMENT DETAILS -->
  </div>
  <!-- END OF DETAILS -->
</div>
<!-- END OF CONTAINER -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fat Dolphin</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900|Montserrat:700&display=swap" rel="stylesheet">  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/notification' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/confirmation.html.erb
<div class="confirmation" >
  <div class="msg">
    <i class="fas fa-check-circle"></i>
    <h3> Your booking has been requested. </h3>
    <p class="first"> The owner has 24h to accept the request. Thank you for trusting <span class="logo">THE FAT DOLPHIN</span>!</p>
    <p> You can view your booking at your <%= link_to "profile", dashboard_path, class: "prof-link" %> page </p>
  </div>
  <div class="btn-confir d-flex justify-content-center ">
    <button class="confir-btn col-md-4 text-center"><%= link_to "Keep Searching", root_path%></button>
  </div>
</div>

app/views/pages/dashboard.html.erb
<!-- show my gear  -->
<div class="container">

<h5 class="text-center pb-2 border-bottom">Check how your gear is doing!</h5>
<h5 class="text-center pb-2">Listed Gear</h5>
<div class="card-gear">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 justify-content-center border-bottom pb-3" >
        <% @user.gears.each do |gear| %>
              <%= link_to gear_path(gear) do %>
              <div class="card-trip m-3">
                <% if gear.photo.attached? %>
                  <%= cl_image_tag gear.photo.key, style:"object-fit: cover; height: 217.8px;" %>
                <% else %>
                  <img class="card-img-top" src="https://images.unsplash.com/photo-1518353053542-7ea33d942319?ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80" alt="Card image cap">
                <% end %>
                <div class="card-trip-infos">
                  <p class="card-title"> <%= gear.name %> </p>

                  <% if gear.available == true %>
                    <p>available</p>
                  <% else %>
                    <p>not available</p>
                  <% end %>
                </div>
              </div>
              <% end %>
        <% end %>
      </div>
</div>
<!-- End of my gear -->

<!-- Show the gear currently hiring -->
<div class="border-bottom">
  <h5 class="text-center py-2">Your listed and rented gear</h5>
  <div class="card-gear">
    <% @rents.each do |rent|  %>
        <p><%= rent.gear.name %></p>
    <% end %>
  </div>
</div>
<div class="border-bottom mb-5 pb-3">
    <h5 class="text-center py-2">Borowed gear</h5>
  <% @gears.each do |gear|  %>
    <% gear.rents.each do |rent| %>
      <p><%= gear.name %></p>
      <% if rent.request == false %>
        <%= simple_form_for [gear, rent], method: :patch do |t| %>
          <%= t.input :request, as: :hidden, html: { value: true }  %>
          <%= t.submit "Accept" %>
        <% end %>

        <%= simple_form_for [gear, rent], method: :delete do |t| %>
          <%= t.submit "Reject" %>
        <% end %>
      <% else %>
        <p>Accepted</p>
      <% end %>
    <% end %>
  <% end %>
</div>
<!-- Show the gear you requested -->


</div>
<!-- END OF CONTAINER -->

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1> Convenient access to all filming gear </h1>
    <p> Rent what you need when you need it. </p>
    <%= render 'shared/search-bar' %>
  </div>
</div>

<div class="container">

  <div class="icons">
    <div class="col-sm-1 col-md-3">
      <div class="icon-card">
        <p><i class="fas fa-thumbs-up"></i></p>
          <p><strong>Access More</strong></p>
          <p>Pursue you're dreams.</p>
      </div>
    </div>
    <div class="col-sm-1 col-md-3">
      <div class="icon-card">
        <p><i class="fab fa-envira"></i></p>
        <div class="icon-text">
          <p><strong>Help the planet</strong></p>
          <p>Live lighter. Reduce waste.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-1 col-md-3">
      <div class="icon-card">
        <p><i class="fas fa-donate"></i></p>
        <div class="icon-text">
          <p><strong>Save money</strong></p>
          <p>Be cost effective.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="popular">
    <h1>- Popular Categories -</h1>
    <div class="cards-container">
      <%=link_to gears_path(utf8: "✓", :query => "cameras", button: ""), style:'text-decoration: none;' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1546687952-19182f36efe6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=357&q=80)">
        Cameras
        </div>
      <% end %>
      <%=link_to gears_path(utf8: "✓", :query => "lenses", button: ""), style:'text-decoration: none;' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://res.cloudinary.com/dvdrzlpz/image/upload/v1582649942/90-angle-W9RHcD0J44Q-unsplash_jita8a.jpg)">
          Lenses
        </div>
      <% end %>
      <%=link_to gears_path(utf8: "✓", :query => "drones", button: ""), style:'text-decoration: none;' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://res.cloudinary.com/dvdrzlpz/image/upload/v1582650148/skye-studios-rjmSbF6TQvQ-unsplash_bcmwtc.jpg)">
          Drones
        </div>
      <% end %>
      <%=link_to gears_path(utf8: "✓", :query => "tripods", button: ""), style:'text-decoration: none;' do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1553288569-8d3d4e12fb02?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80)">
          Tripods
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <%= review.description %>
  <%= review.rating %>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@gear, @review] do |t| %>
        <%= t.input :description %>
        <%= t.input :rating %>

        <%= t.submit "Add Review", class: "btn btn-primary btn-block" %>
        <% end %>

app/views/shared/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1516724562728-afc824a36e84?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80)">
  Cameras
</div>

app/views/shared/_footer.html.erb
<!-- <footer class="site-footer">
  <div id="footer-content">
    <p>Copyright 2017 @ Domain - All Rights Reserved </p>
  </div>
</footer>
 -->

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span>The Fat Dolphin</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
         <%=link_to current_user.username, dashboard_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "List Gear", new_gear_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <!-- <li><%= current_user.username %></li> -->
            <%= link_to "List Gear", new_gear_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span>The Fat Dolphin</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "List Gear", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "List Gear", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_notification.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_search-bar.html.erb
<div class="search-bar">
      <%= form_tag gears_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: "  Search for equipment", class: "input-query"%>
        <%= button_tag(type: "submit", class: "search-btn") do %>
            <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>